version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: teste-omega
    restart: unless-stopped
    environment:
      POSTGRES_USER: omega_user
      POSTGRES_PASSWORD: omega_password
      POSTGRES_DB: omega_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - omega-network
    

volumes:
  postgres_data:

networks:
  omega-network:
    driver: bridge